# Headless service for the StatefulSet members
apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  labels:
    role: mongo
spec:
  ports:
  - name: mongo-0
    port: 27017
    targetPort: 27017
    nodePort: 31117
  - name: mongo-1
    port: 27017
    targetPort: 27017
    nodePort: 31118
  - name: mongo-2
    port: 27017
    targetPort: 27017
    nodePort: 31119
  selector:
    role: mongo
  type: NodePort