#
# Circle CI 2.0 Docs
# 
# For info, see: https://circleci.com/docs/2.0/
#

# This file contains all the builds for devops 
# when something changes everything is rebuild and pushed.
# Not ideal but hell ...

version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
    environment:
      - DOCKER-GRPC-TOOLS_VERSION: "0.1"
    working_directory: ~/devops
    steps:
      - checkout
      - setup_remote_docker

      # Build and Push to Docker Hub (latest and circleci version'd) 
      - run: |
            TAG=$DOCKER-GRPC-TOOLS_VERSION.$CIRCLE_BUILD_NUM
            docker build -t newtonsystems/tools-docker-grpc-tools ./tools/docker-grpc-tools
            docker build -t newtonsystems/tools-docker-grpc-tools:$TAG ./tools/docker-grpc-tools
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push newtonsystems/tools-docker-grpc-tools:latest
            docker push newtonsystems/tools-docker-grpc-tools:$TAG
