apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: agent-mgmt
  name: agent-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      run: agent-mgmt
  template:
    metadata:
      labels:
        run: agent-mgmt
    spec:
      containers:
      - image: newtonsystems/agent-mgmt:master
        imagePullPolicy: Always
        name: agent-mgmt
        env:
        - name: MONGO_DB
          value: "master"
        ports:
        - containerPort: 50000

