apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: hello:local
        args: ["app"]
        name: hello
        #env:
        # - name: POD_NAME
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.name
        # - name: POD_IP
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.podIP
        # - name: NS
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.namespace
        #- name: http_proxy
        #  value: http://192.168.99.100:4140
        ports:
        - containerPort: 50000
