apiVersion: v1
kind: Service
metadata:
  labels:
    run: agent-mgmt
  name: agent-mgmt
spec:
  ports:
  - name: debug
    port: 8080
  - name: outgoing
    port: 27017
  - name: grpc
    port: 50000
    protocol: TCP
  selector:
    run: agent-mgmt
  type: NodePort
