apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: agent-mgmt
  name: agent-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      run: agent-mgmt
  template:
    metadata:
      labels:
        run: agent-mgmt
    spec:
      containers:
      - image: newtonsystems/agent-mgmt:master
        name: agent-mgmt
        ports:
        - containerPort: 50000
        - containerPort: 27017
        volumeMounts:
        - name: agent-mgmt-storage
          mountPath:  /go/src/github.com/newtonsystems/agent-mgmt
      volumes:
      - name: agent-mgmt-storage
        hostPath:
          # directory location on host
          path: /Users/danvir/go/src/github.com/newtonsystems/agent-mgmt